/* Generated by Yosys 0.55 (git sha1 60f126cd0, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module FPAdd_5_10_F400_uid2(clk, rst, X, Y, R);
  wire [5:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire [17:0] _011_;
  wire [10:0] _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire [1:0] _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire [1:0] _041_;
  wire _042_;
  wire _043_;
  reg [17:0] _044_;
  wire _045_;
  reg [17:0] _046_;
  reg [17:0] _047_;
  reg [17:0] _048_;
  reg [4:0] _049_;
  reg [4:0] _050_;
  reg [4:0] _051_;
  reg [1:0] _052_;
  reg _053_;
  reg _054_;
  reg _055_;
  wire _056_;
  reg _057_;
  reg _058_;
  reg _059_;
  reg _060_;
  reg [5:0] _061_;
  reg [1:0] _062_;
  reg [1:0] _063_;
  reg [1:0] _064_;
  reg [1:0] _065_;
  reg [1:0] _066_;
  wire _067_;
  reg _068_;
  reg _069_;
  reg _070_;
  reg _071_;
  reg _072_;
  reg [5:0] _073_;
  reg [23:0] _074_;
  reg [6:0] _075_;
  reg [6:0] _076_;
  reg _077_;
  wire _078_;
  reg [1:0] _079_;
  reg [9:0] _080_;
  reg [4:0] _081_;
  wire _082_;
  wire _083_;
  wire [5:0] _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire [17:0] _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire [1:0] _147_;
  wire _148_;
  wire _149_;
  wire [17:0] _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire [5:0] _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire [3:0] _158_;
  wire [23:0] _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire [13:0] _163_;
  wire _164_;
  wire _165_;
  wire [13:0] _166_;
  wire [6:0] _167_;
  wire [3:0] _168_;
  wire [14:0] _169_;
  wire [6:0] _170_;
  wire _171_;
  output [17:0] R;
  wire [17:0] R;
  input [17:0] X;
  wire [17:0] X;
  input [17:0] Y;
  wire [17:0] Y;
  wire addtoroundbit;
  wire cinaddfar;
  input clk;
  wire clk;
  wire [17:0] computedr;
  wire effsub;
  wire effsub_d1;
  wire effsub_d2;
  wire effsub_d3;
  wire effsub_d4;
  wire effsub_d5;
  wire effsub_d6;
  wire [13:0] effsubvector;
  wire eqdiffsign;
  wire eqdiffsign_d1;
  wire [16:0] excexpfracx;
  wire [16:0] excexpfracy;
  wire [1:0] excr;
  wire [1:0] excrt;
  wire [1:0] excrt2;
  wire [1:0] excrt_d1;
  wire [1:0] excrt_d2;
  wire [1:0] excrt_d3;
  wire [1:0] excrt_d4;
  wire [1:0] excrt_d5;
  wire [1:0] excx;
  wire [1:0] excy;
  wire [1:0] excy_d1;
  wire [3:0] exexpexc;
  wire [5:0] exmey;
  wire [5:0] expdiff;
  wire [5:0] expdiff_d1;
  wire [17:0] expfrac;
  wire [4:0] expr;
  wire [4:0] expr_d1;
  wire [4:0] expx;
  wire [4:0] expx_d1;
  wire [4:0] expx_d2;
  wire [4:0] expx_d3;
  wire [6:0] extendedexpinc;
  wire [6:0] extendedexpinc_d1;
  wire [6:0] extendedexpinc_d2;
  wire [5:0] eymex;
  wire [13:0] \fracadder:232 ;
  wire [13:0] fracaddresult;
  wire [14:0] fracgrs;
  wire [9:0] fracr;
  wire [9:0] fracr_d1;
  wire [13:0] fracxfar;
  wire [10:0] fracy;
  wire [13:0] fracyfar;
  wire [13:0] fracyfarxorop;
  wire grd;
  wire lsb;
  wire [3:0] \lzc_component:241 ;
  wire [14:0] \lzc_component:242 ;
  wire [17:0] newx;
  wire [17:0] newx_d1;
  wire [17:0] newx_d2;
  wire [17:0] newx_d3;
  wire [17:0] newy;
  wire [17:0] newy_d1;
  wire [3:0] nzerosnew;
  wire [23:0] \rightshiftercomponent:207 ;
  wire rnd;
  wire [17:0] roundedexpfrac;
  wire [17:0] \roundingadder:273 ;
  input rst;
  wire rst;
  wire [14:0] shiftedfrac;
  wire [23:0] shiftedfracy;
  wire [23:0] shiftedfracy_d1;
  wire shiftedout;
  wire [3:0] shiftval;
  wire signr;
  wire signr2;
  wire signr_d1;
  wire signr_d2;
  wire signr_d3;
  wire signr_d4;
  wire signr_d5;
  wire signx;
  wire signx_d1;
  wire signy;
  wire sticky;
  wire stk;
  wire swap;
  wire [5:0] sxsyexnxy;
  wire [5:0] sxsyexnxy_d1;
  wire [6:0] updatedexp;
  wire [1:0] upexc;
  wire [1:0] upexc_d1;
  assign _085_ = sxsyexnxy_d1 == 6'h15;
  assign _086_ = _083_ | _085_;
  assign _087_ = sxsyexnxy_d1 == 6'h25;
  assign _088_ = _086_ | _087_;
  assign _089_ = sxsyexnxy_d1 == 6'h35;
  assign _090_ = _088_ | _089_;
  assign _091_ = sxsyexnxy_d1 == 6'h04;
  assign _092_ = _090_ | _091_;
  assign _093_ = sxsyexnxy_d1 == 6'h14;
  assign _094_ = _092_ | _093_;
  assign _096_ = sxsyexnxy_d1 == 6'h24;
  assign _097_ = _094_ | _096_;
  assign _098_ = sxsyexnxy_d1 == 6'h34;
  assign _099_ = _097_ | _098_;
  assign _100_ = sxsyexnxy_d1 == 6'h01;
  assign _101_ = _099_ | _100_;
  assign _102_ = sxsyexnxy_d1 == 6'h11;
  assign _103_ = _101_ | _102_;
  assign _104_ = sxsyexnxy_d1 == 6'h21;
  assign _105_ = _103_ | _104_;
  assign _107_ = sxsyexnxy_d1 == 6'h31;
  assign _108_ = _105_ | _107_;
  assign _109_ = sxsyexnxy_d1 == 6'h3a;
  assign _110_ = sxsyexnxy_d1 == 6'h0a;
  assign _111_ = _109_ | _110_;
  assign _112_ = sxsyexnxy_d1 == 6'h08;
  assign _113_ = _111_ | _112_;
  assign _114_ = sxsyexnxy_d1 == 6'h18;
  assign _115_ = _113_ | _114_;
  assign _116_ = sxsyexnxy_d1 == 6'h28;
  assign _118_ = _115_ | _116_;
  assign _119_ = sxsyexnxy_d1 == 6'h38;
  assign _120_ = _118_ | _119_;
  assign _121_ = sxsyexnxy_d1 == 6'h02;
  assign _122_ = _120_ | _121_;
  assign _123_ = sxsyexnxy_d1 == 6'h12;
  assign _124_ = _122_ | _123_;
  assign _125_ = sxsyexnxy_d1 == 6'h22;
  assign _126_ = _124_ | _125_;
  assign _127_ = sxsyexnxy_d1 == 6'h32;
  assign _129_ = _126_ | _127_;
  assign _130_ = sxsyexnxy_d1 == 6'h09;
  assign _131_ = _129_ | _130_;
  assign _132_ = sxsyexnxy_d1 == 6'h19;
  assign _133_ = _131_ | _132_;
  assign _134_ = sxsyexnxy_d1 == 6'h29;
  assign _135_ = _133_ | _134_;
  assign _136_ = sxsyexnxy_d1 == 6'h39;
  assign _137_ = _135_ | _136_;
  assign _138_ = sxsyexnxy_d1 == 6'h06;
  assign _140_ = _137_ | _138_;
  assign _141_ = sxsyexnxy_d1 == 6'h16;
  assign _142_ = _140_ | _141_;
  assign _143_ = sxsyexnxy_d1 == 6'h26;
  assign _144_ = _142_ | _143_;
  assign _145_ = sxsyexnxy_d1 == 6'h36;
  assign _146_ = _144_ | _145_;
  function [1:0] \:188 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:188  = b[1:0];
      3'b?1?:
        \:188  = b[3:2];
      3'b1??:
        \:188  = b[5:4];
      default:
        \:188  = a;
    endcase
  endfunction
  assign _147_ = \:188 (2'h3, 6'h24, { _146_, _108_, _082_ });
  assign _148_ = sxsyexnxy_d1 == 6'h20;
  assign _149_ = sxsyexnxy_d1 == 6'h10;
  assign _151_ = _148_ | _149_;
  assign _152_ = _151_ ? 1'h0 : signx_d1;
  assign _153_ = ~ swap;
  assign _154_ = _153_ ? exmey : eymex;
  assign _155_ = expdiff_d1 > 6'h0c;
  assign _156_ = _155_ ? 1'h1 : 1'h0;
  assign _157_ = ~ shiftedout;
  assign _158_ = _157_ ? expdiff_d1[3:0] : 4'hd;
  assign _160_ = shiftedfracy_d1[10:0] == 11'h000;
  assign _162_ = _160_ ? 1'h0 : 1'h1;
  assign _163_ = fracyfar ^ effsubvector;
  assign _164_ = ~ sticky;
  assign _165_ = effsub_d3 & _164_;
  assign _167_ = { 2'h0, expx_d3 } + 7'h01;
  assign _170_ = extendedexpinc_d2 - { 3'h0, nzerosnew };
  assign _171_ = nzerosnew == 4'hf;
  assign _002_ = _171_ ? 1'h1 : 1'h0;
  assign _003_ = shiftedfrac[1] | shiftedfrac[0];
  assign _004_ = ~ lsb;
  assign _005_ = grd & _004_;
  assign _006_ = ~ rnd;
  assign _007_ = _006_ & _005_;
  assign _008_ = ~ stk;
  assign _009_ = _008_ & _007_;
  assign _010_ = _009_ ? 1'h0 : 1'h1;
  assign _013_ = exexpexc == 4'h0;
  assign _014_ = exexpexc == 4'h4;
  assign _015_ = _013_ | _014_;
  assign _016_ = exexpexc == 4'h8;
  assign _017_ = _015_ | _016_;
  assign _018_ = exexpexc == 4'hc;
  assign _019_ = _017_ | _018_;
  assign _020_ = exexpexc == 4'h9;
  assign _021_ = _019_ | _020_;
  assign _022_ = exexpexc == 4'hd;
  assign _024_ = _021_ | _022_;
  assign _025_ = exexpexc == 4'h1;
  assign _026_ = exexpexc == 4'h2;
  assign _027_ = exexpexc == 4'h6;
  assign _028_ = _026_ | _027_;
  assign _029_ = exexpexc == 4'ha;
  assign _030_ = _028_ | _029_;
  assign _031_ = exexpexc == 4'he;
  assign _032_ = _030_ | _031_;
  assign _033_ = exexpexc == 4'h5;
  assign _035_ = _032_ | _033_;
  function [1:0] \:318 ;
    input [1:0] a;
    input [5:0] b;
    input [2:0] s;
    (* parallel_case *)
    casez (s)
      3'b??1:
        \:318  = b[1:0];
      3'b?1?:
        \:318  = b[3:2];
      3'b1??:
        \:318  = b[5:4];
      default:
        \:318  = a;
    endcase
  endfunction
  assign _036_ = \:318 (2'h3, 6'h24, { _035_, _025_, _024_ });
  assign _037_ = effsub_d6 & eqdiffsign_d1;
  assign _038_ = excrt_d5 == 2'h3;
  assign _039_ = ~ _038_;
  assign _040_ = _039_ & _037_;
  assign _041_ = _040_ ? 2'h0 : excrt2;
  assign _042_ = effsub_d6 & eqdiffsign_d1;
  assign _043_ = _042_ ? 1'h0 : signr_d5;
  always @(posedge clk)
    _044_ <= newx;
  always @(posedge clk)
    _046_ <= newx_d1;
  always @(posedge clk)
    _047_ <= newx_d2;
  always @(posedge clk)
    _048_ <= newy;
  always @(posedge clk)
    _049_ <= expx;
  always @(posedge clk)
    _050_ <= expx_d1;
  always @(posedge clk)
    _051_ <= expx_d2;
  always @(posedge clk)
    _052_ <= excy;
  always @(posedge clk)
    _053_ <= signx;
  always @(posedge clk)
    _054_ <= effsub;
  always @(posedge clk)
    _055_ <= effsub_d1;
  always @(posedge clk)
    _057_ <= effsub_d2;
  always @(posedge clk)
    _058_ <= effsub_d3;
  always @(posedge clk)
    _059_ <= effsub_d4;
  always @(posedge clk)
    _060_ <= effsub_d5;
  always @(posedge clk)
    _061_ <= sxsyexnxy;
  always @(posedge clk)
    _062_ <= excrt;
  always @(posedge clk)
    _063_ <= excrt_d1;
  always @(posedge clk)
    _064_ <= excrt_d2;
  always @(posedge clk)
    _065_ <= excrt_d3;
  always @(posedge clk)
    _066_ <= excrt_d4;
  always @(posedge clk)
    _068_ <= signr;
  always @(posedge clk)
    _069_ <= signr_d1;
  always @(posedge clk)
    _070_ <= signr_d2;
  always @(posedge clk)
    _071_ <= signr_d3;
  always @(posedge clk)
    _072_ <= signr_d4;
  always @(posedge clk)
    _073_ <= expdiff;
  always @(posedge clk)
    _074_ <= shiftedfracy;
  always @(posedge clk)
    _075_ <= extendedexpinc;
  always @(posedge clk)
    _076_ <= extendedexpinc_d1;
  always @(posedge clk)
    _077_ <= eqdiffsign;
  always @(posedge clk)
    _079_ <= upexc;
  always @(posedge clk)
    _080_ <= fracr;
  always @(posedge clk)
    _081_ <= expr;
  assign _000_ = { 1'h0, X[14:10] } - { 1'h0, Y[14:10] };
  assign _084_ = { 1'h0, Y[14:10] } - { 1'h0, X[14:10] };
  assign _095_ = excexpfracx >= excexpfracy;
  assign _106_ = _095_ ? 1'h0 : 1'h1;
  assign _117_ = ~ swap;
  assign _128_ = _117_ ? X : Y;
  assign _139_ = ~ swap;
  assign _150_ = _139_ ? Y : X;
  assign _161_ = signx ^ signy;
  assign _001_ = excy_d1 == 2'h0;
  assign _012_ = _001_ ? 11'h000 : { 1'h1, newy_d1[9:0] };
  assign _023_ = sxsyexnxy_d1 == 6'h00;
  assign _034_ = sxsyexnxy_d1 == 6'h10;
  assign _045_ = _023_ | _034_;
  assign _056_ = sxsyexnxy_d1 == 6'h20;
  assign _067_ = _045_ | _056_;
  assign _078_ = sxsyexnxy_d1 == 6'h30;
  assign _082_ = _067_ | _078_;
  assign _083_ = sxsyexnxy_d1 == 6'h05;
  intadder_14_f400_uid8 fracadder (
    .cin(cinaddfar),
    .clk(clk),
    .r(_166_),
    .rst(rst),
    .x(fracxfar),
    .y(fracyfarxorop)
  );
  lzcshifter_15_to_15_counting_16_f400_uid16 lzc_component (
    .clk(clk),
    .count(_168_),
    .i(fracgrs),
    .o(_169_),
    .rst(rst)
  );
  rightshifter_11_by_max_13_f400_uid4 rightshiftercomponent (
    .clk(clk),
    .r(_159_),
    .rst(rst),
    .s(shiftval),
    .x(fracy)
  );
  intadder_18_f400_uid20 roundingadder (
    .cin(addtoroundbit),
    .clk(clk),
    .r(_011_),
    .rst(rst),
    .x(expfrac),
    .y(18'h00000)
  );
  assign excexpfracx = { X[17:16], X[14:0] };
  assign excexpfracy = { Y[17:16], Y[14:0] };
  assign exmey = _000_;
  assign eymex = _084_;
  assign swap = _106_;
  assign newx = _128_;
  assign newx_d1 = _044_;
  assign newx_d2 = _046_;
  assign newx_d3 = _047_;
  assign newy = _150_;
  assign newy_d1 = _048_;
  assign expx = newx[14:10];
  assign expx_d1 = _049_;
  assign expx_d2 = _050_;
  assign expx_d3 = _051_;
  assign excx = newx[17:16];
  assign excy = newy[17:16];
  assign excy_d1 = _052_;
  assign signx = newx[15];
  assign signx_d1 = _053_;
  assign signy = newy[15];
  assign effsub = _161_;
  assign effsub_d1 = _054_;
  assign effsub_d2 = _055_;
  assign effsub_d3 = _057_;
  assign effsub_d4 = _058_;
  assign effsub_d5 = _059_;
  assign effsub_d6 = _060_;
  assign sxsyexnxy = { signx, signy, excx, excy };
  assign sxsyexnxy_d1 = _061_;
  assign fracy = _012_;
  assign excrt = _147_;
  assign excrt_d1 = _062_;
  assign excrt_d2 = _063_;
  assign excrt_d3 = _064_;
  assign excrt_d4 = _065_;
  assign excrt_d5 = _066_;
  assign signr = _152_;
  assign signr_d1 = _068_;
  assign signr_d2 = _069_;
  assign signr_d3 = _070_;
  assign signr_d4 = _071_;
  assign signr_d5 = _072_;
  assign expdiff = _154_;
  assign expdiff_d1 = _073_;
  assign shiftedout = _156_;
  assign shiftval = _158_;
  assign shiftedfracy = \rightshiftercomponent:207 ;
  assign shiftedfracy_d1 = _074_;
  assign sticky = _162_;
  assign fracyfar = { 1'h0, shiftedfracy_d1[23:11] };
  assign effsubvector = { effsub_d3, effsub_d3, effsub_d3, effsub_d3, effsub_d3, effsub_d3, effsub_d3, effsub_d3, effsub_d3, effsub_d3, effsub_d3, effsub_d3, effsub_d3, effsub_d3 };
  assign fracyfarxorop = _163_;
  assign fracxfar = { 2'h1, newx_d3[9:0], 2'h0 };
  assign cinaddfar = _165_;
  assign fracaddresult = \fracadder:232 ;
  assign fracgrs = { fracaddresult, sticky };
  assign extendedexpinc = _167_;
  assign extendedexpinc_d1 = _075_;
  assign extendedexpinc_d2 = _076_;
  assign nzerosnew = \lzc_component:241 ;
  assign shiftedfrac = \lzc_component:242 ;
  assign updatedexp = _170_;
  assign eqdiffsign = _002_;
  assign eqdiffsign_d1 = _077_;
  assign expfrac = { updatedexp, shiftedfrac[13:3] };
  assign stk = _003_;
  assign rnd = shiftedfrac[2];
  assign grd = shiftedfrac[3];
  assign lsb = shiftedfrac[4];
  assign addtoroundbit = _010_;
  assign roundedexpfrac = \roundingadder:273 ;
  assign upexc = roundedexpfrac[17:16];
  assign upexc_d1 = _079_;
  assign fracr = roundedexpfrac[10:1];
  assign fracr_d1 = _080_;
  assign expr = roundedexpfrac[15:11];
  assign expr_d1 = _081_;
  assign exexpexc = { upexc_d1, excrt_d5 };
  assign excrt2 = _036_;
  assign excr = _041_;
  assign signr2 = _043_;
  assign computedr = { excr, signr2, expr_d1, fracr_d1 };
  assign \rightshiftercomponent:207  = _159_;
  assign \fracadder:232  = _166_;
  assign \lzc_component:241  = _168_;
  assign \lzc_component:242  = _169_;
  assign \roundingadder:273  = _011_;
  assign R = computedr;
endmodule

module intadder_14_f400_uid8(clk, rst, x, y, cin, r);
  wire [13:0] _0_;
  wire [13:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [13:0] r;
  wire [13:0] r;
  input rst;
  wire rst;
  input [13:0] x;
  wire [13:0] x;
  input [13:0] y;
  wire [13:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 13'h0000, cin };
  assign r = _1_;
endmodule

module intadder_18_f400_uid20(clk, rst, x, y, cin, r);
  wire [17:0] _0_;
  wire [17:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [17:0] r;
  wire [17:0] r;
  input rst;
  wire rst;
  input [17:0] x;
  wire [17:0] x;
  input [17:0] y;
  wire [17:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 17'h00000, cin };
  assign r = _1_;
endmodule

module lzcshifter_15_to_15_counting_16_f400_uid16(clk, rst, i, count, o);
  wire _00_;
  wire _01_;
  wire _02_;
  wire [14:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [14:0] _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire [14:0] _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [14:0] _15_;
  reg _16_;
  reg _17_;
  reg [14:0] _18_;
  reg _19_;
  reg _20_;
  reg [14:0] _21_;
  input clk;
  wire clk;
  output [3:0] count;
  wire [3:0] count;
  wire count0;
  wire count1;
  wire count1_d1;
  wire count2;
  wire count2_d1;
  wire count3;
  wire count3_d1;
  wire count3_d2;
  input [14:0] i;
  wire [14:0] i;
  wire [14:0] level0;
  wire [14:0] level1;
  wire [14:0] level1_d1;
  wire [14:0] level2;
  wire [14:0] level3;
  wire [14:0] level3_d1;
  wire [14:0] level4;
  output [14:0] o;
  wire [14:0] o;
  input rst;
  wire rst;
  wire [3:0] scount;
  assign _00_ = level4[14:7] == 8'h00;
  assign _01_ = _00_ ? 1'h1 : 1'h0;
  assign _02_ = ~ count3;
  assign _03_ = _02_ ? level4 : { level4[6:0], 8'h00 };
  assign _04_ = level3_d1[14:11] == 4'h0;
  assign _05_ = _04_ ? 1'h1 : 1'h0;
  assign _06_ = ~ count2;
  assign _07_ = _06_ ? level3_d1 : { level3_d1[10:0], 4'h0 };
  assign _08_ = level2[14:13] == 2'h0;
  assign _09_ = _08_ ? 1'h1 : 1'h0;
  assign _10_ = ~ count1;
  assign _11_ = _10_ ? level2 : { level2[12:0], 2'h0 };
  assign _12_ = level1_d1[14] == 1'h0;
  assign _13_ = _12_ ? 1'h1 : 1'h0;
  assign _14_ = ~ count0;
  assign _15_ = _14_ ? level1_d1 : { level1_d1[13:0], 1'h0 };
  always @(posedge clk)
    _16_ <= count3;
  always @(posedge clk)
    _17_ <= count3_d1;
  always @(posedge clk)
    _18_ <= level3;
  always @(posedge clk)
    _19_ <= count2;
  always @(posedge clk)
    _20_ <= count1;
  always @(posedge clk)
    _21_ <= level1;
  assign level4 = i;
  assign count3 = _01_;
  assign count3_d1 = _16_;
  assign count3_d2 = _17_;
  assign level3 = _03_;
  assign level3_d1 = _18_;
  assign count2 = _05_;
  assign count2_d1 = _19_;
  assign level2 = _07_;
  assign count1 = _09_;
  assign count1_d1 = _20_;
  assign level1 = _11_;
  assign level1_d1 = _21_;
  assign count0 = _13_;
  assign level0 = _15_;
  assign scount = { count3_d2, count2_d1, count1_d1, count0 };
  assign count = scount;
  assign o = level0;
endmodule

module rightshifter_11_by_max_13_f400_uid4(clk, rst, x, s, r);
  wire [11:0] _0_;
  wire [13:0] _1_;
  wire [17:0] _2_;
  wire [25:0] _3_;
  reg [3:0] _4_;
  reg [17:0] _5_;
  input clk;
  wire clk;
  wire [10:0] level0;
  wire [11:0] level1;
  wire [13:0] level2;
  wire [17:0] level3;
  wire [17:0] level3_d1;
  wire [25:0] level4;
  wire [3:0] ps;
  wire [3:0] ps_d1;
  output [23:0] r;
  wire [23:0] r;
  input rst;
  wire rst;
  input [3:0] s;
  wire [3:0] s;
  input [10:0] x;
  wire [10:0] x;
  assign _0_ = ps[0] ? { 1'h0, level0 } : { level0, 1'h0 };
  assign _1_ = ps[1] ? { 2'h0, level1 } : { level1, 2'h0 };
  assign _2_ = ps[2] ? { 4'h0, level2 } : { level2, 4'h0 };
  assign _3_ = ps_d1[3] ? { 8'h00, level3_d1 } : { level3_d1, 8'h00 };
  always @(posedge clk)
    _4_ <= ps;
  always @(posedge clk)
    _5_ <= level3;
  assign level0 = x;
  assign ps = s;
  assign ps_d1 = _4_;
  assign level1 = _0_;
  assign level2 = _1_;
  assign level3 = _2_;
  assign level3_d1 = _5_;
  assign level4 = _3_;
  assign r = level4[25:2];
endmodule
