/* Generated by Yosys 0.55 (git sha1 60f126cd0, g++ 13.3.0-6ubuntu2~24.04 -fPIC -O3) */

module FPSqrt_5_10(clk, rst, X, R);
  wire [4:0] _000_;
  wire _001_;
  reg [2:0] _002_;
  reg [4:0] _003_;
  reg [4:0] _004_;
  reg [4:0] _005_;
  reg [4:0] _006_;
  reg [4:0] _007_;
  reg [4:0] _008_;
  reg [4:0] _009_;
  reg [4:0] _010_;
  reg [4:0] _011_;
  wire _012_;
  reg [4:0] _013_;
  reg [4:0] _014_;
  reg [4:0] _015_;
  reg [13:0] _016_;
  reg [1:0] _017_;
  reg [13:0] _018_;
  reg [2:0] _019_;
  reg [13:0] _020_;
  reg [3:0] _021_;
  reg [13:0] _022_;
  wire [4:0] _023_;
  reg [4:0] _024_;
  reg [13:0] _025_;
  reg [5:0] _026_;
  reg [13:0] _027_;
  reg [6:0] _028_;
  reg [13:0] _029_;
  reg [7:0] _030_;
  reg [13:0] _031_;
  reg [8:0] _032_;
  reg [13:0] _033_;
  wire _034_;
  reg [9:0] _035_;
  reg [13:0] _036_;
  reg [10:0] _037_;
  reg [13:0] _038_;
  reg [11:0] _039_;
  reg [11:0] _040_;
  reg _041_;
  wire [4:0] _042_;
  wire [4:0] _043_;
  wire _044_;
  wire _045_;
  wire [5:0] _046_;
  wire _047_;
  wire [4:0] _048_;
  wire [5:0] _049_;
  wire [5:0] _050_;
  wire _051_;
  wire _052_;
  wire [6:0] _053_;
  wire _054_;
  wire [6:0] _055_;
  wire [6:0] _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire [7:0] _060_;
  wire _061_;
  wire [7:0] _062_;
  wire [7:0] _063_;
  wire _064_;
  wire _065_;
  wire [8:0] _066_;
  wire _067_;
  wire [8:0] _068_;
  wire [8:0] _069_;
  wire [13:0] _070_;
  wire _071_;
  wire _072_;
  wire [9:0] _073_;
  wire _074_;
  wire [9:0] _075_;
  wire [9:0] _076_;
  wire _077_;
  wire _078_;
  wire [10:0] _079_;
  wire _080_;
  wire _081_;
  wire [10:0] _082_;
  wire [10:0] _083_;
  wire _084_;
  wire _085_;
  wire [11:0] _086_;
  wire _087_;
  wire [11:0] _088_;
  wire [11:0] _089_;
  wire _090_;
  wire _091_;
  wire [3:0] _092_;
  wire [12:0] _093_;
  wire _094_;
  wire [12:0] _095_;
  wire [12:0] _096_;
  wire _097_;
  wire _098_;
  wire [13:0] _099_;
  wire _100_;
  wire [13:0] _101_;
  wire [13:0] _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire [14:0] _106_;
  wire _107_;
  wire [14:0] _108_;
  wire [14:0] _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire [3:0] _114_;
  wire [11:0] _115_;
  wire _116_;
  wire _117_;
  wire [9:0] _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire [2:0] _123_;
  reg [2:0] _124_;
  wire [3:0] _125_;
  reg [2:0] _126_;
  reg [2:0] _127_;
  reg [2:0] _128_;
  reg [2:0] _129_;
  reg [2:0] _130_;
  reg [2:0] _131_;
  reg [2:0] _132_;
  reg [2:0] _133_;
  reg [2:0] _134_;
  reg [2:0] _135_;
  output [17:0] R;
  wire [17:0] R;
  input [17:0] X;
  wire [17:0] X;
  input clk;
  wire clk;
  wire d0;
  wire d1;
  wire d10;
  wire d11;
  wire d12;
  wire d2;
  wire d3;
  wire d4;
  wire d5;
  wire d6;
  wire d7;
  wire d8;
  wire d9;
  wire [14:0] ds1;
  wire [5:0] ds10;
  wire [4:0] ds11;
  wire [3:0] ds12;
  wire [13:0] ds2;
  wire [12:0] ds3;
  wire [11:0] ds4;
  wire [10:0] ds5;
  wire [9:0] ds6;
  wire [8:0] ds7;
  wire [7:0] ds8;
  wire [6:0] ds9;
  wire [4:0] ern0;
  wire [4:0] ern1;
  wire [4:0] ern1_d1;
  wire [4:0] ern1_d10;
  wire [4:0] ern1_d11;
  wire [4:0] ern1_d12;
  wire [4:0] ern1_d2;
  wire [4:0] ern1_d3;
  wire [4:0] ern1_d4;
  wire [4:0] ern1_d5;
  wire [4:0] ern1_d6;
  wire [4:0] ern1_d7;
  wire [4:0] ern1_d8;
  wire [4:0] ern1_d9;
  wire [13:0] fr;
  wire [9:0] fracx;
  wire [11:0] frn1;
  wire [11:0] frn1_d1;
  wire [9:0] frn2;
  wire [14:0] rn2;
  wire round;
  wire round_d1;
  input rst;
  wire rst;
  wire [11:0] s1;
  wire [2:0] s10;
  wire [2:0] s10_d1;
  wire [1:0] s11;
  wire [1:0] s11_d1;
  wire s12;
  wire [11:0] s1_d1;
  wire [10:0] s2;
  wire [10:0] s2_d1;
  wire [9:0] s3;
  wire [9:0] s3_d1;
  wire [8:0] s4;
  wire [8:0] s4_d1;
  wire [7:0] s5;
  wire [7:0] s5_d1;
  wire [6:0] s6;
  wire [6:0] s6_d1;
  wire [5:0] s7;
  wire [5:0] s7_d1;
  wire [4:0] s8;
  wire [4:0] s8_d1;
  wire [3:0] s9;
  wire [3:0] s9_d1;
  wire [13:0] w1;
  wire [13:0] w10;
  wire [13:0] w10_d1;
  wire [13:0] w11;
  wire [13:0] w11_d1;
  wire [13:0] w12;
  wire [13:0] w13;
  wire [13:0] w1_d1;
  wire [13:0] w2;
  wire [13:0] w2_d1;
  wire [13:0] w3;
  wire [13:0] w3_d1;
  wire [13:0] w4;
  wire [13:0] w4_d1;
  wire [13:0] w5;
  wire [13:0] w5_d1;
  wire [13:0] w6;
  wire [13:0] w6_d1;
  wire [13:0] w7;
  wire [13:0] w7_d1;
  wire [13:0] w8;
  wire [13:0] w8_d1;
  wire [13:0] w9;
  wire [13:0] w9_d1;
  wire [14:0] wh1;
  wire [5:0] wh10;
  wire [4:0] wh11;
  wire [3:0] wh12;
  wire [13:0] wh2;
  wire [12:0] wh3;
  wire [11:0] wh4;
  wire [10:0] wh5;
  wire [9:0] wh6;
  wire [8:0] wh7;
  wire [7:0] wh8;
  wire [6:0] wh9;
  wire [14:0] x1;
  wire [14:0] x10;
  wire [14:0] x11;
  wire [14:0] x12;
  wire [14:0] x2;
  wire [14:0] x3;
  wire [14:0] x4;
  wire [14:0] x5;
  wire [14:0] x6;
  wire [14:0] x7;
  wire [14:0] x8;
  wire [14:0] x9;
  wire [14:0] xh1;
  wire [5:0] xh10;
  wire [4:0] xh11;
  wire [3:0] xh12;
  wire [13:0] xh2;
  wire [12:0] xh3;
  wire [11:0] xh4;
  wire [10:0] xh5;
  wire [9:0] xh6;
  wire [8:0] xh7;
  wire [7:0] xh8;
  wire [6:0] xh9;
  wire [2:0] xsr;
  wire [2:0] xsx;
  wire [2:0] xsx_d1;
  wire [2:0] xsx_d10;
  wire [2:0] xsx_d11;
  wire [2:0] xsx_d12;
  wire [2:0] xsx_d2;
  wire [2:0] xsx_d3;
  wire [2:0] xsx_d4;
  wire [2:0] xsx_d5;
  wire [2:0] xsx_d6;
  wire [2:0] xsx_d7;
  wire [2:0] xsx_d8;
  wire [2:0] xsx_d9;
  assign _023_ = xh11 - ds11;
  assign _034_ = d11 == 1'h0;
  assign _042_ = xh11 + ds11;
  function [4:0] \:107 ;
    input [4:0] a;
    input [4:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:107  = b[4:0];
      default:
        \:107  = a;
    endcase
  endfunction
  assign _043_ = \:107 (_042_, _023_, _034_);
  assign _044_ = ~ d11;
  assign _045_ = ~ d10;
  assign _046_ = xh10 - ds10;
  assign _047_ = d10 == 1'h0;
  assign _049_ = xh10 + ds10;
  function [5:0] \:128 ;
    input [5:0] a;
    input [5:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:128  = b[5:0];
      default:
        \:128  = a;
    endcase
  endfunction
  assign _050_ = \:128 (_049_, _046_, _047_);
  assign _051_ = ~ d10;
  assign _052_ = ~ d9;
  assign _053_ = xh9 - ds9;
  assign _054_ = d9 == 1'h0;
  assign _055_ = xh9 + ds9;
  function [6:0] \:149 ;
    input [6:0] a;
    input [6:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:149  = b[6:0];
      default:
        \:149  = a;
    endcase
  endfunction
  assign _056_ = \:149 (_055_, _053_, _054_);
  assign _057_ = ~ d9;
  assign _058_ = ~ d8;
  assign _060_ = xh8 - ds8;
  assign _061_ = d8 == 1'h0;
  assign _062_ = xh8 + ds8;
  function [7:0] \:170 ;
    input [7:0] a;
    input [7:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:170  = b[7:0];
      default:
        \:170  = a;
    endcase
  endfunction
  assign _063_ = \:170 (_062_, _060_, _061_);
  assign _064_ = ~ d8;
  assign _065_ = ~ d7;
  assign _066_ = xh7 - ds7;
  assign _067_ = d7 == 1'h0;
  assign _068_ = xh7 + ds7;
  function [8:0] \:191 ;
    input [8:0] a;
    input [8:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:191  = b[8:0];
      default:
        \:191  = a;
    endcase
  endfunction
  assign _069_ = \:191 (_068_, _066_, _067_);
  assign _071_ = ~ d7;
  assign _072_ = ~ d6;
  assign _073_ = xh6 - ds6;
  assign _074_ = d6 == 1'h0;
  assign _075_ = xh6 + ds6;
  function [9:0] \:212 ;
    input [9:0] a;
    input [9:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:212  = b[9:0];
      default:
        \:212  = a;
    endcase
  endfunction
  assign _076_ = \:212 (_075_, _073_, _074_);
  assign _077_ = ~ d6;
  assign _078_ = ~ d5;
  assign _079_ = xh5 - ds5;
  assign _080_ = d5 == 1'h0;
  assign _082_ = xh5 + ds5;
  function [10:0] \:233 ;
    input [10:0] a;
    input [10:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:233  = b[10:0];
      default:
        \:233  = a;
    endcase
  endfunction
  assign _083_ = \:233 (_082_, _079_, _080_);
  assign _084_ = ~ d5;
  assign _085_ = ~ d4;
  assign _086_ = xh4 - ds4;
  assign _087_ = d4 == 1'h0;
  assign _088_ = xh4 + ds4;
  function [11:0] \:254 ;
    input [11:0] a;
    input [11:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:254  = b[11:0];
      default:
        \:254  = a;
    endcase
  endfunction
  assign _089_ = \:254 (_088_, _086_, _087_);
  assign _090_ = ~ d4;
  assign _091_ = ~ d3;
  assign _093_ = xh3 - ds3;
  assign _094_ = d3 == 1'h0;
  assign _095_ = xh3 + ds3;
  function [12:0] \:275 ;
    input [12:0] a;
    input [12:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:275  = b[12:0];
      default:
        \:275  = a;
    endcase
  endfunction
  assign _096_ = \:275 (_095_, _093_, _094_);
  assign _097_ = ~ d3;
  assign _098_ = ~ d2;
  assign _099_ = xh2 - ds2;
  assign _100_ = d2 == 1'h0;
  assign _101_ = xh2 + ds2;
  function [13:0] \:296 ;
    input [13:0] a;
    input [13:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:296  = b[13:0];
      default:
        \:296  = a;
    endcase
  endfunction
  assign _102_ = \:296 (_101_, _099_, _100_);
  assign _104_ = ~ d2;
  assign _105_ = ~ d1;
  assign _106_ = xh1 - ds1;
  assign _107_ = d1 == 1'h0;
  assign _108_ = xh1 + ds1;
  function [14:0] \:316 ;
    input [14:0] a;
    input [14:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:316  = b[14:0];
      default:
        \:316  = a;
    endcase
  endfunction
  assign _109_ = \:316 (_108_, _106_, _107_);
  assign _110_ = ~ d1;
  assign _111_ = ~ d0;
  assign _112_ = fr[1] | fr[0];
  assign _113_ = fr[13] == 1'h1;
  function [11:0] \:334 ;
    input [11:0] a;
    input [11:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:334  = b[11:0];
      default:
        \:334  = a;
    endcase
  endfunction
  assign _115_ = \:334 (fr[11:0], { fr[12:2], _112_ }, _113_);
  assign _116_ = frn1[2] | frn1[0];
  assign _117_ = frn1[1] & _116_;
  assign _118_ = frn1_d1[11:2] + { 9'h000, round_d1 };
  assign _119_ = xsx_d12 == 3'h2;
  assign _120_ = xsx_d12 == 3'h4;
  assign _121_ = xsx_d12 == 3'h0;
  assign _122_ = xsx_d12 == 3'h1;
  function [2:0] \:359 ;
    input [2:0] a;
    input [11:0] b;
    input [3:0] s;
    (* parallel_case *)
    casez (s)
      4'b???1:
        \:359  = b[2:0];
      4'b??1?:
        \:359  = b[5:3];
      4'b?1??:
        \:359  = b[8:6];
      4'b1???:
        \:359  = b[11:9];
      default:
        \:359  = a;
    endcase
  endfunction
  assign _123_ = \:359 (3'h6, 12'h222, { _122_, _121_, _120_, _119_ });
  always @(posedge clk)
    _124_ <= xsx;
  always @(posedge clk)
    _126_ <= xsx_d1;
  always @(posedge clk)
    _127_ <= xsx_d2;
  always @(posedge clk)
    _128_ <= xsx_d3;
  always @(posedge clk)
    _129_ <= xsx_d4;
  always @(posedge clk)
    _130_ <= xsx_d5;
  always @(posedge clk)
    _131_ <= xsx_d6;
  always @(posedge clk)
    _132_ <= xsx_d7;
  always @(posedge clk)
    _133_ <= xsx_d8;
  always @(posedge clk)
    _134_ <= xsx_d9;
  always @(posedge clk)
    _135_ <= xsx_d10;
  always @(posedge clk)
    _002_ <= xsx_d11;
  always @(posedge clk)
    _003_ <= ern1;
  always @(posedge clk)
    _004_ <= ern1_d1;
  always @(posedge clk)
    _005_ <= ern1_d2;
  always @(posedge clk)
    _006_ <= ern1_d3;
  always @(posedge clk)
    _007_ <= ern1_d4;
  always @(posedge clk)
    _008_ <= ern1_d5;
  always @(posedge clk)
    _009_ <= ern1_d6;
  always @(posedge clk)
    _010_ <= ern1_d7;
  always @(posedge clk)
    _011_ <= ern1_d8;
  always @(posedge clk)
    _013_ <= ern1_d9;
  always @(posedge clk)
    _014_ <= ern1_d10;
  always @(posedge clk)
    _015_ <= ern1_d11;
  always @(posedge clk)
    _016_ <= w11;
  always @(posedge clk)
    _017_ <= s11;
  always @(posedge clk)
    _018_ <= w10;
  always @(posedge clk)
    _019_ <= s10;
  always @(posedge clk)
    _020_ <= w9;
  always @(posedge clk)
    _021_ <= s9;
  always @(posedge clk)
    _022_ <= w8;
  always @(posedge clk)
    _024_ <= s8;
  always @(posedge clk)
    _025_ <= w7;
  always @(posedge clk)
    _026_ <= s7;
  always @(posedge clk)
    _027_ <= w6;
  always @(posedge clk)
    _028_ <= s6;
  always @(posedge clk)
    _029_ <= w5;
  always @(posedge clk)
    _030_ <= s5;
  always @(posedge clk)
    _031_ <= w4;
  always @(posedge clk)
    _032_ <= s4;
  always @(posedge clk)
    _033_ <= w3;
  always @(posedge clk)
    _035_ <= s3;
  always @(posedge clk)
    _036_ <= w2;
  always @(posedge clk)
    _037_ <= s2;
  always @(posedge clk)
    _038_ <= w1;
  always @(posedge clk)
    _039_ <= s1;
  always @(posedge clk)
    _040_ <= frn1;
  always @(posedge clk)
    _041_ <= round;
  assign _000_ = ern0 + 5'h07;
  assign _048_ = _000_ + { 4'h0, X[10] };
  assign _059_ = ~ X[10];
  assign _070_ = _059_ ? { 3'h7, fracx, 1'h0 } : { 4'hd, fracx };
  assign _081_ = ~ d12;
  assign _092_ = xh12 - ds12;
  assign _103_ = d12 == 1'h0;
  assign _114_ = xh12 + ds12;
  function [3:0] \:86 ;
    input [3:0] a;
    input [3:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:86  = b[3:0];
      default:
        \:86  = a;
    endcase
  endfunction
  assign _125_ = \:86 (_114_, _092_, _103_);
  assign _001_ = ~ d12;
  assign _012_ = ~ d11;
  assign fracx = X[9:0];
  assign ern0 = { 1'h0, X[14:11] };
  assign xsx = X[17:15];
  assign xsx_d1 = _124_;
  assign xsx_d2 = _126_;
  assign xsx_d3 = _127_;
  assign xsx_d4 = _128_;
  assign xsx_d5 = _129_;
  assign xsx_d6 = _130_;
  assign xsx_d7 = _131_;
  assign xsx_d8 = _132_;
  assign xsx_d9 = _133_;
  assign xsx_d10 = _134_;
  assign xsx_d11 = _135_;
  assign xsx_d12 = _002_;
  assign ern1 = _048_;
  assign ern1_d1 = _003_;
  assign ern1_d2 = _004_;
  assign ern1_d3 = _005_;
  assign ern1_d4 = _006_;
  assign ern1_d5 = _007_;
  assign ern1_d6 = _008_;
  assign ern1_d7 = _009_;
  assign ern1_d8 = _010_;
  assign ern1_d9 = _011_;
  assign ern1_d10 = _013_;
  assign ern1_d11 = _014_;
  assign ern1_d12 = _015_;
  assign w13 = _070_;
  assign d12 = w13[13];
  assign x12 = { w13, 1'h0 };
  assign ds12 = { 1'h0, _081_, d12, 1'h1 };
  assign xh12 = x12[14:11];
  assign wh12 = _125_;
  assign w12 = { wh12[2:0], x12[10:0] };
  assign s12 = _001_;
  assign d11 = w12[13];
  assign x11 = { w12, 1'h0 };
  assign ds11 = { 1'h0, s12, _012_, d11, 1'h1 };
  assign xh11 = x11[14:10];
  assign wh11 = _043_;
  assign w11 = { wh11[3:0], x11[9:0] };
  assign w11_d1 = _016_;
  assign s11 = { s12, _044_ };
  assign s11_d1 = _017_;
  assign d10 = w11_d1[13];
  assign x10 = { w11_d1, 1'h0 };
  assign ds10 = { 1'h0, s11_d1, _045_, d10, 1'h1 };
  assign xh10 = x10[14:9];
  assign wh10 = _050_;
  assign w10 = { wh10[4:0], x10[8:0] };
  assign w10_d1 = _018_;
  assign s10 = { s11_d1, _051_ };
  assign s10_d1 = _019_;
  assign d9 = w10_d1[13];
  assign x9 = { w10_d1, 1'h0 };
  assign ds9 = { 1'h0, s10_d1, _052_, d9, 1'h1 };
  assign xh9 = x9[14:8];
  assign wh9 = _056_;
  assign w9 = { wh9[5:0], x9[7:0] };
  assign w9_d1 = _020_;
  assign s9 = { s10_d1, _057_ };
  assign s9_d1 = _021_;
  assign d8 = w9_d1[13];
  assign x8 = { w9_d1, 1'h0 };
  assign ds8 = { 1'h0, s9_d1, _058_, d8, 1'h1 };
  assign xh8 = x8[14:7];
  assign wh8 = _063_;
  assign w8 = { wh8[6:0], x8[6:0] };
  assign w8_d1 = _022_;
  assign s8 = { s9_d1, _064_ };
  assign s8_d1 = _024_;
  assign d7 = w8_d1[13];
  assign x7 = { w8_d1, 1'h0 };
  assign ds7 = { 1'h0, s8_d1, _065_, d7, 1'h1 };
  assign xh7 = x7[14:6];
  assign wh7 = _069_;
  assign w7 = { wh7[7:0], x7[5:0] };
  assign w7_d1 = _025_;
  assign s7 = { s8_d1, _071_ };
  assign s7_d1 = _026_;
  assign d6 = w7_d1[13];
  assign x6 = { w7_d1, 1'h0 };
  assign ds6 = { 1'h0, s7_d1, _072_, d6, 1'h1 };
  assign xh6 = x6[14:5];
  assign wh6 = _076_;
  assign w6 = { wh6[8:0], x6[4:0] };
  assign w6_d1 = _027_;
  assign s6 = { s7_d1, _077_ };
  assign s6_d1 = _028_;
  assign d5 = w6_d1[13];
  assign x5 = { w6_d1, 1'h0 };
  assign ds5 = { 1'h0, s6_d1, _078_, d5, 1'h1 };
  assign xh5 = x5[14:4];
  assign wh5 = _083_;
  assign w5 = { wh5[9:0], x5[3:0] };
  assign w5_d1 = _029_;
  assign s5 = { s6_d1, _084_ };
  assign s5_d1 = _030_;
  assign d4 = w5_d1[13];
  assign x4 = { w5_d1, 1'h0 };
  assign ds4 = { 1'h0, s5_d1, _085_, d4, 1'h1 };
  assign xh4 = x4[14:3];
  assign wh4 = _089_;
  assign w4 = { wh4[10:0], x4[2:0] };
  assign w4_d1 = _031_;
  assign s4 = { s5_d1, _090_ };
  assign s4_d1 = _032_;
  assign d3 = w4_d1[13];
  assign x3 = { w4_d1, 1'h0 };
  assign ds3 = { 1'h0, s4_d1, _091_, d3, 1'h1 };
  assign xh3 = x3[14:2];
  assign wh3 = _096_;
  assign w3 = { wh3[11:0], x3[1:0] };
  assign w3_d1 = _033_;
  assign s3 = { s4_d1, _097_ };
  assign s3_d1 = _035_;
  assign d2 = w3_d1[13];
  assign x2 = { w3_d1, 1'h0 };
  assign ds2 = { 1'h0, s3_d1, _098_, d2, 1'h1 };
  assign xh2 = x2[14:1];
  assign wh2 = _102_;
  assign w2 = { wh2[12:0], x2[0] };
  assign w2_d1 = _036_;
  assign s2 = { s3_d1, _104_ };
  assign s2_d1 = _037_;
  assign d1 = w2_d1[13];
  assign x1 = { w2_d1, 1'h0 };
  assign ds1 = { 1'h0, s2_d1, _105_, d1, 1'h1 };
  assign xh1 = x1;
  assign wh1 = _109_;
  assign w1 = wh1[13:0];
  assign w1_d1 = _038_;
  assign s1 = { s2_d1, _110_ };
  assign s1_d1 = _039_;
  assign d0 = w1_d1[13];
  assign fr = { s1_d1, _111_, 1'h1 };
  assign frn1 = _115_;
  assign frn1_d1 = _040_;
  assign round = _117_;
  assign round_d1 = _041_;
  assign frn2 = _118_;
  assign rn2 = { ern1_d12, frn2 };
  assign xsr = _123_;
  assign R = { xsr, rn2 };
endmodule
